[package]

name = "dogfights"
version = "0.0.1"
authors = [ "Francesco Mazzoli <f@mazzo.li>" ]

[lib]
name = "dogfights-lib"
path = "src/main.rs"

[[bin]]
name = "dogfights"
path = "src/dogfights.rs"

[[bin]]
name = "dogfights-server"
path = "src/dogfights-server.rs"

[[bin]]
name = "dogfights-remote"
path = "src/dogfights-remote.rs"

[dependencies.sdl2]
# git = "https://github.com/AngryLawyer/rust-sdl2"
path = "/home/bitonic/src/rust-sdl2"

[dependencies.sdl2_image]
# git = "https://github.com/bitonic/rust-sdl2_image"
path = "/home/bitonic/src/rust-sdl2_image"

[dependencies]
rustc-serialize = "0.2.1"

[dependencies.bincode]
# git = "https://github.com/TyOverby/bincode"
path = "/home/bitonic/src/bincode"
