[package]

name = "asteroidi"
version = "0.0.1"
authors = [ "Francesco Mazzoli <f@mazzo.li>" ]

[[bin]]

name = "asteroidi"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies.sdl2_image]
git = "https://github.com/bitonic/rust-sdl2_image"
