[package]

name = "dogfights"
version = "0.0.1"
authors = [ "Francesco Mazzoli <f@mazzo.li>" ]

[[bin]]

name = "dogfights"

[dependencies.sdl2]
git = "https://github.com/jameson-ernst/rust-sdl2"

[dependencies.sdl2_image]
path = "/home/bitonic/src/rust-sdl2_image"

[dependencies]
rustc-serialize = "0.1.5"

[dependencies.bincode]
git = "https://github.com/TyOverby/bincode"