[package]
name = "ai"
version = "0.0.1"
authors = ["Francesco Mazzoli <f@mazzo.li>"]

[lib]
name = "ai"
path = "lib.rs"

[dependencies.actors]
path = "../actors"

[dependencies.input]
path = "../input"
