[package]
name = "specs"
version = "0.0.1"
authors = ["Francesco Mazzoli <f@mazzo.li>"]

[lib]
name = "specs"
path = "lib.rs"

[dependencies]
rustc-serialize = "^0"
sdl2 = "^0"

[dependencies.geometry]
path = "../geometry"

[dependencies.conf]
path = "../conf"
